apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: victoria-metrics
data:
  datasources.yaml: |-
    apiVersion: 1
    datasources:
    - name: VictoriaMetrics
      type: prometheus
      url: http://vmsingle-example-vmsingle.victoria-metrics.svc:8429
      access: proxy
      isDefault: true
