apiVersion: v1
kind: Service
metadata:
  name: vmsingle-service
  namespace: victoria-metrics
spec:
  selector:
    app.kubernetes.io/name: vmsingle
    app.kubernetes.io/instance: example-vmsingle
  type: NodePort
  ports:
  - name: http
    port: 8428
    targetPort: 8428
    nodePort: 30001
