apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: websocket-exporter
  namespace: victoria-metrics
spec:
  selector:
    matchLabels:
      app: websocket-exporter
  endpoints:
  - port: http
    path: /metrics
    interval: 15s
